# Site settings
title: "liam"
description: "Download the liam program."
baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: "https://liamyang.github.io/"
author: "Liam Yang"

# Build settings
kramdown:
  input: GFM
permalink: pretty

plugins:
  - jekyll-algolia

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
